APP_NAME="Milonga"
APP_VERSION="0.1.51"
APP_ENVIROMENT="dev"
APP_PORT="8921"
APP_URL="http://127.0.0.1"
APP_VIEW_PATH="./web/views"
APP_LOG_PATH="logs/error.log"
APP_OPENINBROWSER=false

DB_CONFIG_PATH="/config/db_config.toml"

# replace this to improve security
JWT_SECRET="jwt-deepest-secret"

# Password token encryption key
# 32 bytes para AES-256
PASSTOKEN_ENCRYPTIONKEY = "01l10kkt9w0YnT8Hm/ts+aOYj6DpgNa1MLF6Xd0iN6w="