APP_NAME="Milonga"
APP_VERSION="0.1.51"
APP_PORT="8922"
APP_URL="http://127.0.0.1"
APP_VIEW_PATH="./web/views"
APP_LOG_PATH="milonga.log"

DB_CONFIG_PATH="/config/db_config.toml"

JWT_SECRET="jwt-deepest-secret"

# Password token encryption key
# 32 bytes para AES-256
PASSTOKEN_ENCRYPTIONKEY = "krI5QldDx3Vk2xUTStUp7czUPPcUnVMHG4IvBZA9CaI="