# engines (sqlite / mysql / postgres)
[[database]]
    connName="local"
    engine="sqlite"
    host=""
    port=""
    user=""
    password=""
    dbname="milonga_db.db"

[[database]]
    connName="mysql-test"
    engine="mysql"
    host="localhost"
    port="3306"
    user="root"
    password="root_password"
    dbname="generic_db"